### ISSUE TITLE
What is a Yarbrough?

### ISSUE THREAD

**Issue by pvtsnuffy** [DC3-VDP/DIB-VDP-Pilot#12]
Line 2 describes a Yarbrough but that is just a mythical creature from an old Pittsburghian tale. Please update to a more applicable Repici; a swamp creature from the New Jersey Pine Barrens that lives on citgo hotdogs and dark magic coffee. Very scary indeed!

**Comment by repicij** [comment]
That would be defined as the Jersey Devil.
